version: '3'
services:
  redis:
    image: redis:6.2.6 
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3001:80'
    depends_on:
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes:
      - /api/node_modules
      - ./api:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      # - /app/node_modules
      - ./client/pages:/app/pages
      - ./client/public:/app/public
      - ./client/styles:/app/styles